name: ci

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    name: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: moonrepo/setup-rust@v1
      - name: Install build deps and run test
        shell: pwsh
        run: |
          ls
          cargo test
